### ISSUE TITLE
llc error: expected top-level entity source_filename = "hello_world.c"

### ISSUE THREAD

**Issue by ghost** [avr-llvm/examples#2]
Hi! I'm getting the error message when I try to compile "hello_world.c":

```
mmathy@ubuntuuu:~/Desktop/examples-master/hello_world$ make -B

clang -c -S -emit-llvm -O --target=avr -mmcu=atmega328p -DF_CPU=16000000 -isystem /usr/lib/avr/include/ hello_world.c -o hello_world.ll

llc -filetype=asm -march=avr -mcpu=atmega328p hello_world.ll -o hello_world.s

llc: hello_world.ll:2:1: error: expected top-level entity
source_filename = "hello_world.c"
^
make: *** [hello_world.s] Error 1
```

What's the problem?
Thanks!

**Comment by dylanmckay** [comment]
can you post the contents of 'hello_world.ll

**Comment by ghost** [comment]
```
; ModuleID = 'hello_world.c'
source_filename = "hello_world.c"
target datalayout = "e-p:16:8:8-i8:8:8-i16:8:8-i32:8:8-i64:8:8-f32:8:8-f64:8:8-n8"
target triple = "avr"

@DELAY_MS = constant i16 1000, align 2

; Function Attrs: norecurse nounwind readnone
define i16 @do_something(i16 %a) #0 {
entry:
  %mul = shl nsw i16 %a, 1
  ret i16 %mul
}

; Function Attrs: noreturn nounwind
define i16 @main() #1 {
entry:
  %0 = load volatile i8, i8* inttoptr (i16 36 to i8*), align 4, !tbaa !1
  %or = or i8 %0, 32
  store volatile i8 %or, i8* inttoptr (i16 36 to i8*), align 4, !tbaa !1
  br label %while.body

while.body:                                       ; preds = %entry, %while.body
  %1 = load volatile i8, i8* inttoptr (i16 37 to i8*), align 1, !tbaa !1
  %or3 = or i8 %1, 32
  store volatile i8 %or3, i8* inttoptr (i16 37 to i8*), align 1, !tbaa !1
  tail call void @__builtin_avr_delay_cycles(i32 16000000) #3
  %2 = load volatile i8, i8* inttoptr (i16 37 to i8*), align 1, !tbaa !1
  %and = and i8 %2, -33
  store volatile i8 %and, i8* inttoptr (i16 37 to i8*), align 1, !tbaa !1
  tail call void @__builtin_avr_delay_cycles(i32 16000000) #3
  br label %while.body
}

declare void @__builtin_avr_delay_cycles(i32) #2

attributes #0 = { norecurse nounwind readnone "disable-tail-calls"="false" "less-precise-fpmad"="false" "no-frame-pointer-elim"="true" "no-frame-pointer-elim-non-leaf" "no-infs-fp-math"="false" "no-jump-tables"="false" "no-nans-fp-math"="false" "stack-protector-buffer-size"="8" "target-cpu"="atmega328p" "unsafe-fp-math"="false" "use-soft-float"="false" }
attributes #1 = { noreturn nounwind "disable-tail-calls"="false" "less-precise-fpmad"="false" "no-frame-pointer-elim"="true" "no-frame-pointer-elim-non-leaf" "no-infs-fp-math"="false" "no-jump-tables"="false" "no-nans-fp-math"="false" "stack-protector-buffer-size"="8" "target-cpu"="atmega328p" "unsafe-fp-math"="false" "use-soft-float"="false" }
attributes #2 = { "disable-tail-calls"="false" "less-precise-fpmad"="false" "no-frame-pointer-elim"="true" "no-frame-pointer-elim-non-leaf" "no-infs-fp-math"="false" "no-nans-fp-math"="false" "stack-protector-buffer-size"="8" "target-cpu"="atmega328p" "unsafe-fp-math"="false" "use-soft-float"="false" }
attributes #3 = { nounwind }

!llvm.ident = !{!0}

!0 = !{!"clang version 3.9.0 (https://github.com/avr-llvm/clang.git ee44fb694684f63e3b7801a56b94f0fbe4d524a5) (llvm/llvm.git 2860030806d0fb22831192835e2e257622d73575)"}
!1 = !{!2, !2, i64 0}
!2 = !{!"omnipotent char", !3, i64 0}
!3 = !{!"Simple C/C++ TBAA"}

```

**Comment by dylanmckay** [comment]
Will take a look at it when I get home. By the way, if you use 3 backticks ``` to start and end your block, it'll put it in a code block.

**Comment by dylanmckay** [comment]
I get the same error when I run `llc` from the system LLVM I have installed (LLVM 3.5). It looks like what's happening is that you're not running the `llc` that you just compiled (inside `bin/`), but you are using the system `llc`.

The syntax has changed since that old version.

**Comment by ghost** [comment]
Yeah man! That's the problem ...
Do you have a Makefile for the entire compiling process (.c ~ .hex ~ avrdude ~ UNO)? I don't know how to generate the .hex file.

**Comment by dylanmckay** [comment]
Nah, don't have a makefile or anything. It should work the _exact_ same as GCC though, if you replace `gcc` with `clang`.

>  I don't know how to generate the .hex file.

You generate an object file with `clang`, you link it to ELF, and you can then use `objcopy` to copy the ELF sections to raw binaries. You can then use another tool (I forgot what it is) to convert the raw binary to a textual intel hex file.

**Comment by shepmaster** [comment]
Once you have the ELF file:

```
avr-objcopy -O ihex -R .eeprom hello.elf hello.hex
avrdude -p atmega328p -c arduino -P /dev/cu.usbmodem1411 -U flash:w:hello.hex:i
```

[More info from the Rust perspective](http://jakegoulding.com/blog/2016/01/17/rust-on-an-arduino-uno-part-2/).

**Comment by ghost** [comment]
> Once you have the ELF file

I do not have the ELF file.

When I compile "hello_world.c":
`clang -c -O --target=avr -mmcu=atmega328p -DF_CPU=16000000 -isystem /usr/lib/avr/include hello_world.c`
everything works fine. The output: "hello_world.o"

But, when I try to link:
`avr-gcc -mmcu=atmega328p hello_world.o -o hello_world.elf`
I get the following **error**:
`hello_world.o: In function `LBB1_1':
hello_world.c:(.text+0x1e): undefined reference to `__builtin_avr_delay_cycles'`

When I try with the avr-gcc:
`avr-gcc -Os -g -std=gnu99 -Wall -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -ffunction-sections -fdata-sections -DF_CPU=16000000UL -mmcu=atmega328p -c -o hello_world.o hello_world.c
avr-gcc -Wl,-Map,hello_world.map -Wl,--gc-sections -mmcu=atmega328p hello_world.o  -o hello_world.elf`
everything works fine. The output: hello_world.elf,  hello_world.map,  hello_world.o

**Comment by ghost** [comment]
Finally... :)
Inside "delay.h" I found this:

`The implementation of _delay_ms() based on
   __builtin_avr_delay_cycles() is not backward compatible with older
   implementations.  In order to get functionality backward compatible
   with previous versions, the macro \c "__DELAY_BACKWARD_COMPATIBLE__"
   must be defined before including this header file. Also, the
   backward compatible algorithm will be chosen if the code is
   compiled in a <em>freestanding environment</em> (GCC option
   \c -ffreestanding), as the math functions required for rounding are
   not available to the compiler then.`

So, when I insert the **DELAY_BACKWARD_COMPATIBLE** macro, everything works fine!

**Comment by dylanmckay** [comment]
Nice :)

**Comment by concatime** [comment]
Thank you infinitely #ghost.
